### ISSUE TITLE
RPi2 problem easily fixed

### ISSUE THREAD

**Issue by zunzun** [pgiri/dispy#19] opened 2015-06-01 11:26 UTC
I wanted to try dispy on a Raspberry Pi 2 (RPi2) cluster, which makes an excellent inexpensive cluster for education.  When I did this, I would initially get failure with errors that read:

Could not send reply for job [job ID]

As it turns out, my relatively high RPi2 ping times over wifi would cause dispynode tomeout errors, and these were easily corrected as follows.

In the file dispynode.py, I changed two settings.  First I increased the value of

MsgTimeout

to 50.  Secondly, there were several hardcoded "settimeout(2)" statements that I changed to be "settimeout(50)".

Now dispy works great over my cheapie wifi network!  This is awesome.  I can use RPi2 or the really cheap C.H.I.P. 9$ computers to teach Python clustering with dispy.

Please consider a timeout command line parameter for slower, cheaper educational wifi networks.  Alternatively some "ping" measurement to test the value, but that seems like overkill.

James Phillips

**Comment by pgiri** [comment] 2015-06-01 12:07
Hi,

I thought MsgTimeout value of 5 seconds "should be enough for everybody"! If you need to increase it by quite a bit, I am guessing you need to change it in 'dispy.py' as well (or, change it in your client program with 'dispy.MsgTimeout = 50'). Making it an option parameter is a good idea; will be done in next release.

The timeout '2' is for UDP (may be these should be renamed TCPTimeout and UDPTimeout), except in a few cases. It shouldn't be necessary to increase them by that much. May be playing with a few settings to see smallest values that work in your case may help? Making timeouts too big means that it takes that long for dispy/dispynode to realize the other end is unreachable in case of true failures.

Thanks,
Giri

**Comment by zunzun** [comment] 2015-06-01 12:38
Good thinking.  In my specific case, I only want to demonstrate that it works.  On cheap hardware - and I mean really, really, really cheap - the timeout must be greater than current defaults.

Perhaps the error message could suggest using the new parameter?  I almost gave up in frustration until I remembered my equipment was, ahhh, "less than ideal".  The technical term most commonly used in the literature to accurately describe my setup is "cheap as doo-doo".

Dispy does work perfectly after the change, and perhaps advice on "large ping times for slower equipment" can be mentioned in the documentation for the new setting, plus a warning that it should not normally need to be changed.

James

**Comment by pgiri** [comment] 2015-06-01 12:50
Hmm, that you had issues with timeout when sending job result but not when client is sending computation / jobs etc. gives me some clues to what the real problem might be.

Are you sending large job result / output? If so, can you try sending smaller job result, output and see if that works with default 5 seconds? My guess is that the problem might be in asyncoro actually, which uses Python socket's 'sendall' to send_msg, which means the timeout specified is for whole message. Splitting this into repetitive 'send' might work for everyone with 5 seconds. May be.

If your problem is reproducible, I could send you modified asyncoro (later this week / weekend) to see if that works.

Giri

**Comment by zunzun** [comment] 2015-06-01 13:08
The problem in my case seems to be a combination of wifi plus slow CPU.  I can easily reproduce the problem, and will gladly make tests as needed.  Note that some hardware setups with new linux-enabled cheap computers will be even slower than what I'm trying.

I am using the simple compute(n) example unchanged from the documentation.

James


James

**Comment by pgiri** [comment] 2015-06-02 09:27
Can you try following changes to asyncoro? These change the way timeouts are used for sendall and recvall (which are used in send_msg / recv_msg that have 5s timeouts in dispynode).

The attached changes to asyncoro and original dispynode (as in 4.3 release) may work. In that case, I would rather go with these changes than to increase timeout to 50 seconds in dispynode. RPi2 may be cheap, but it is not that slow - many users seem to be using dispy, likely with ethernet. Is it possible your wifi is slow? 5 seconds should be enough to transmit at least a few kilobytes.

I don't know if the attached patch shows properly for you (I don't see how I can attach a file with this chat); if not, the patch context should help you understand and you can patch manually?

    --- ../asyncoro-3.2/py2/asyncoro/__init__.py    2015-03-15 09:47:22.703728085 -0400
    +++ asyncoro.py 2015-06-01 16:01:42.224123413 -0400
    @@ -371,6 +371,9 @@
                             coro, self._read_coro = self._read_coro, None
                             coro._proceed_(buf)
                         else:
    +                        if self._timeout:
    +                            self._notifier._del_timeout(self)
    +                            self._notifier._add_timeout(self)
                             self._read_task = functools.partial(_recvall, self, view, *args)
                     else:
                         self._notifier.clear(self, _AsyncPoller._Read)
    @@ -514,6 +517,9 @@
                 else:
                     if sent > 0:
                         self._write_result = self._write_result[sent:]
    +                    if self._timeout:
    +                        self._notifier._del_timeout(self)
    +                        self._notifier._add_timeout(self)
                         if len(self._write_result) == 0:
                             self._notifier.clear(self, _AsyncPoller._Write)
                             self._write_task = self._write_result = None

**Comment by zunzun** [comment] 2015-06-02 13:19
Starting now.

James

**Comment by zunzun** [comment] 2015-06-02 14:55
No change.  My test procedure as follows:

1) Backup original __init__.py in asyncoro directory
2) Apply patch
3) Verify patch with diff
4) delete all *.pyc files in asyncoro directory
5) run my previous test with original timeouts - same problem
6) restore original __init__.py in asyncoro
7) delete all *.pyc files in asyncoro directory
8) run my previous test with original timeouts - same problem

9) run my previous test again using new timeouts of "50" to verify - no problem, works fine

James

**Comment by zunzun** [comment] 2015-06-03 11:32
I thought of another test.

I am running with my Python client on a laptop that is connected to my home network via wifi, and dispynode running on a Raspberry Pi 2 connected to my home network via ethernet cable.  Both computers are running Debian 8 (named "jessie") since I don't use Miker-slop's consumer grade crapware.

What I can do is run both the client and dispynode on the RPi2 at the same time.  I had given dispynode the "-i" command for the DHCP address the Pi was assigned, I can also try without this parameter when both are running on the Pi.

Starting now.

James

**Comment by zunzun** [comment] 2015-06-03 13:28
For this test, I ran dispynode on the RPi2 as before.

When I run the client on the same RPi2, no failures or errors.  Perfect operation.

I make no change to the running dispynode.

I then run the client on my laptop, and see the errors as before with failure.

So *my home network* does require larger-than-default timeout values in dispynode.  A command-;ine timeout value, plus a suggestion to try it in the dispynode error message, seems a good working solution for my case.

Is the root cause my ISP, my hardware, my wireless router, government snooping, alien brain control, etc.?  None of those things are dispy, which proveably and repeatedly works well.

James

**Comment by pgiri** [comment] 2015-06-03 13:55
I have already made changes to dispynode, dispyscheduler to have an option to set timeout. I will commit that soon and will be in next release.

I don't know why your setup requires more than 5 seconds to send small amount of data (I think less than 1KB). You can run bandwidth test, for example http://www.speakeasy.net/speedtest/, to test wifi, and then test ethernet to see if the problem is wifi on RPi2 and/or router.

**Comment by zunzun** [comment] 2015-06-03 14:44
I do not get the error on every single transmit, rather every third or fourth send.  I have tested but not found why this happens on my setup; all network tests - other than dispy - do not indicate a problem.  Dispy highlights but does not cause the problem.  In my past experience alien brain control was not corrected by increasing timeout values, so I am going to tentatively rule that out - pending further testing.

All joking aside, there is some problem that cannot be in dispy itself.  Your change is sufficient for my case, and thank you.

James

**Closed** 2015-06-03 14:44 UTC
