### ISSUE TITLE
communication between cluster and nodes lost

### ISSUE THREAD

**Issue by wsfax** [pgiri/dispy#30] opened 2016-03-14 10:13 UTC
I have a program that open a cluster and runs several tasks in parallel on different nodes.
All the nodes are running in the same machine as the cluster so there is no cross machine communication. 
Cluster distributes jobs and nodes reply with results; suddenly after sometime the communication between the two parties seems to be lost. **This continues until python crashes.**

dispy version: 4.6.0
asyncoro version: 3.5

Logs:

**cluster:**
_2016-03-14 11:03:58,898 - dispy - Failed to run job 106591360 on 192.168.13.58 for computation launch_datadumper; rescheduling it
Failed to run job 106591360 on 192.168.13.58 for computation launch_datadumper; rescheduling it
2016-03-14 11:03:58,898 - dispy - Failed to run job 106591120 on 192.168.13.58 for computation launch_datadumper; rescheduling it
Failed to run job 106591120 on 192.168.13.58 for computation launch_datadumper; rescheduling it
2016-03-14 11:03:59,134 - dispy - Could not connect to 192.168.13.58:51348, Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\gulbis\ext\dispy\__init__.py", line 377, in send
    resp = yield sock.recv_msg()
  File "C:\Anaconda2\lib\site-packages\gulbis\ext\asyncoro\__init__.py", line 3224, in _schedule
    retval = coro._generator.throw(*exc)
  File "C:\Anaconda2\lib\site-packages\gulbis\ext\asyncoro\__init__.py", line 682, in _async_recv_msg
    data = yield self.recvall(n)
timeout: timed out

Could not connect to 192.168.13.58:51348, Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\gulbis\ext\dispy\__init__.py", line 377, in send
    resp = yield sock.recv_msg()
  File "C:\Anaconda2\lib\site-packages\gulbis\ext\asyncoro\__init__.py", line 3224, in _schedule
    retval = coro._generator.throw(*exc)
  File "C:\Anaconda2\lib\site-packages\gulbis\ext\asyncoro\__init__.py", line 682, in _async_recv_msg
    data = yield self.recvall(n)
timeout: timed out

2016-03-14 11:03:59,134 - dispy - Could not connect to 192.168.13.58:51348, Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\gulbis\ext\dispy\__init__.py", line 377, in send
    resp = yield sock.recv_msg()
  File "C:\Anaconda2\lib\site-packages\gulbis\ext\asyncoro\__init__.py", line 3224, in _schedule
    retval = coro._generator.throw(*exc)
  File "C:\Anaconda2\lib\site-packages\gulbis\ext\asyncoro\__init__.py", line 682, in _async_recv_msg
    data = yield self.recvall(n)
timeout: timed out_

**nodes:**
_2016-03-14 11:03:09,302 - dispynode - Sending result for job 106361024 (11) to ('192.168.13.58', 51347)
2016-03-14 11:03:09,334 - dispynode - Sending result for job 106361624 (11) to ('192.168.13.58', 51347)
2016-03-14 11:03:10,099 - dispynode - New job id 106414512 from 192.168.13.58/192.168.13.58
2016-03-14 11:03:10,647 - dispynode - Sending result for job 106361744 (11) to ('192.168.13.58', 51347)
2016-03-14 11:03:10,647 - dispynode - Sending result for job 106361264 (11) to ('192.168.13.58', 51347)
2016-03-14 11:03:13,334 - dispynode - Sending result for job 106194408 (11) to ('192.168.13.58', 51347)
2016-03-14 11:03:15,131 - dispynode - Could not send reply for job 106305840 to ('192.168.13.58', 51347); saving it in "c:\users\gulbis~1\appdata\local\temp\dispy\node\192.168.13.58\launch_datadumper_jzeduy\_dispy_job_reply_106305840"
Could not send reply for job 106305840 to ('192.168.13.58', 51347); saving it in "c:\users\gulbis~1\appdata\local\temp\dispy\node\192.168.13.58\launch_datadumper_jzeduy\_dispy_job_reply_106305840"
2016-03-14 11:03:15,381 - dispynode - New job id 106414632 from 192.168.13.58/192.168.13.58
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Anaconda2\lib\site-packages\gulbis\ext\asyncoro\__init__.py", line 3176, in _schedule
    self._notifier.poll(0)
  File "C:\Anaconda2\lib\site-packages\gulbis\ext\asyncoro\__init__.py", line 1035, in poll
    fd._timed_out()
  File "C:\Anaconda2\lib\site-packages\gulbis\ext\asyncoro\__init__.py", line 1124, in _timed_out
    if self._rsock.type & socket.SOCK_STREAM:
AttributeError: 'NoneType' object has no attribute 'type'_

**Comment by wsfax** [comment] 2016-03-14 12:07
forgot to mention that the problem can be fixed by changing the source code of asyncoro line 673:

def _async_recv_msg(self):
        self._timeout = 30
        n = struct.calcsize('>L')

basically increasing the timeout from 5 to 30. 

Now the question is; how to change that timeout value from within dispy ??

**Comment by pgiri** [comment] 2016-03-14 12:16
Can you try latest version of dispy (4.6.10 as of now)?

**Comment by wsfax** [comment] 2016-03-14 12:30
problem not seen in 4.6.10.

could you mention in which version exactly this fix was introduced? could you also explain how it is fixed? (i mean what was exactly wrong)

**Comment by pgiri** [comment] 2016-03-14 12:49
If the problem is because you are transferring large files, the fix was in 4.6.5; see [News](https://sourceforge.net/p/dispy/news/) or github commit log.

**Comment by wsfax** [comment] 2016-03-14 12:53
thanks.

according to 4.6.5 release note: 

> Now MsgTimeout is for transferring at most 1MB of data

does that mean if I transfer 2MB there will be not timeout ?

**Comment by pgiri** [comment] 2016-03-14 13:05
MsgTimeout (say, 10 sec) is used in socket for each I/O operation. Prior to 4.6.5, when a large file is being transferred, 10 sec timeout is used for each _sendall_ which can take the buffer (say, 1MB) and return immediately, so another chunk is sent right away. However, after kernel's buffers are full, _sendall_ can take longer until kernel frees its own buffers, which can take longer than 10 sec (because the buffers have accumulated totaling some arbitrary size, depending on socket / kernel's algorithms), causing dispy's file transfer to fail.

The new behavior is to define MsgTimeout as timeout for sending up to 1MB _chunk_ of data. So if you send 2MB of data, it will first send 1MB chunk; if it takes longer than MsgTimeout for that, timeout exception is raised. If first chunk is successfully received, next chunk is sent using MsgTimeout again etc.

github commit log may also help.

**Comment by wsfax** [comment] 2016-03-14 13:12
thank you for the explanation. it made things clear to me. Also thank you for this very valuable project.

i will close the bug

**Closed** 2016-03-23 19:13 UTC
